# Site settings
baseurl = "https://adamtervort.com/"
title = "Adam Tervort"
paginate = 12
buildFuture = true
theme = "story"
languageCode = "en-US"

googleAnalytics = "UA-128042666-5"

[[menu.social]]
  name = "Twitter"
  title = "fab fa-twitter-square"
  url = "https://twitter.com/adamtervort"

[[menu.social]]
  name = "LinkedIn"
  title = "fab fa-linkedin"
  url = "https://linkedin.com/in/adam-tervort"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"

[[menu.main]]
  name = "About"
  title = "About"
  url = "/about/"

[[menu.main]]
  name = "Contact"
  title = "Contact"
  url = "/contact/"  

[[menu.main]]
  name = "Categories"
  title = "Categories"
  url = "/tags/"

[[menu.main]]
  name = "Speeches"
  title = "Speeches"
  url = "/great-speeches/"

#[[menu.main]]
#  name = "Courses"
#  title = "Courses"
#  url = "https://learn.hammock.marketing/"   

[params]
  author = "Adam Tervort"
  twitter = "adamtervort"
  classes = []
  mailchimp = "https://adamtervort.us20.list-manage.com/subscribe?u=65d2ac8fd182c7884008dd22b&id=9460147e2c"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]

[Permalinks]                                          #### Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
  posts = ":year/:month/:filename"

[privacy]                                             #### Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

[sitemap]                                             #### Sitemap Info
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
