---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Articles
  create: all
  match: "*"
- type: directory
  path: content/search
  label: Search
  create: all
  match: "**/*"
- type: directory
  path: content/mailchimp
  label: Mailchimp
  create: all
  match: "**/*"
- type: directory
  path: content/img
  label: Img
  create: all
  match: "**/*"
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
- type: directory
  path: content/archives
  label: Archives
  create: all
  match: "**/*"
- type: directory
  path: content/2020
  label: '2020'
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.58.3
